const SequenceIds = {
  CONFIG_INIT: 0, // Not used anymore, see 24
  INITIAL_PARAMS: 1,
  RUN_INIT: 2,
  CONFIRM_POS: 3,
  RERUN_INIT: 4,
  CONFIRM: 5,
  OPTIMIZE_POS: 6,
  OPTIMIZED_POS: 7,
  RERUN_OPTIMIZATION: 8,
  END: 9,
  CHANGE_INPUT_GAIN: 10,
  CHANGE_INPUTS_GAIN: 11,
  CHANGE_INPUT_EQ_GAIN: 12,
  CHANGE_MAIN_VOLUME_INPUT: 13,
  CHANGE_MAIN_VOLUME_INPUTS: 14,
  CHANGE_AUX_VOLUME_INPUT: 15,
  CHANGE_AUX_VOLUME_INPUTS: 16,
  CHANGE_MAIN_EQ_OUTPUT_GAINS: 17,
  CHANGE_AUX_EQ_OUTPUT_GAINS: 18,
  CHANGE_MAIN_VOLUME_OUTPUT: 19,
  CHANGE_AUX_VOLUME_OUTPUT: 20,
  ERROR_RATE: 21,
  INPUT_SPECTRUM: 22,
  PEAKMETER_LEVELS: 23,
  CONFIG_CHOICE: 24,
  PROBE_LISTEN: 25,
  STOP_PROBE_LISTEN: 26
};

export default SequenceIds;
