const SequenceIds = {
  CONFIG_CHOICE: 0,
  INITIAL_PARAMS: 1,
  RUN_INIT: 2,
  CONFIRM_POS: 3,
  RERUN_INIT: 4,
  CONFIRM: 5,
  OPTIMIZE_POS: 6,
  OPTIMIZED_POS: 7,
  RERUN_OPTIMIZATION: 8,
  END: 9,
  CHANGE_INPUT_GAIN: 10,
  CHANGE_INPUTS_GAIN: 11,
  CHANGE_INPUT_EQ_GAIN: 12,
  CHANGE_MAIN_VOLUME_INPUT: 13,
  CHANGE_AUX_VOLUME_INPUT: 14,
  CHANGE_MAIN_EQ_OUTPUT_GAINS: 15,
  CHANGE_AUX_EQ_OUTPUT_GAINS: 16,
  CHANGE_MAIN_VOLUME_OUTPUT: 17,
  CHANGE_AUX_VOLUME_OUTPUT: 18,
  ERROR_RATE: 19,
  INPUT_SPECTRUM: 20,
  PEAKMETER_LEVELS: 21
};

export default SequenceIds;
