const steps = {
  'INITIAL_PARAMETERS': 0,
  'PROBE_POSITIONING': 1,
  'PROBE_INITIALIZATON': 2,
  'PROBE_POSITIONS': 3,
  'OPTIMIZATION': 4,
  'OPTIMAL_POSITIONS': 5,
  'COMPLETE': 6
}

export default steps;
